### PR TITLE
subsidy coefficient calculation

### PR DESCRIPTION
**Pull request by chaosma**
* add coefficient calculation related codes 
* end to end test passed
* TODO: order checking on coeff calculation; subsidy results calculation based on coefficient

### CODE REVIEW

**Comment by daodesigner** [comment]
Is this for pairwise subsidies?

**Comment by gurrpi** [comment]
Download link for `CoefficientPerBatch_10-1-2_test.0.zkey` seems to be provided for Testing section of [MACI site](https://appliedzkp.github.io/maci/testing.html#compile-or-download-the-witness-generation-binaries).

**Comment by chaosma** [comment]
> Is this for pairwise subsidies?

yes, that's right

**Comment by chaosma** [comment]
> It seems download link of `CoefficientPerBatch_10-1-2_test.0.zkey` should provided on Testing section of [MACI site](https://appliedzkp.github.io/maci/testing.html#download-zkey-files).

Sure, who can help to upload the file?

**Comment by gurrpi** [comment]
> > It seems download link of `CoefficientPerBatch_10-1-2_test.0.zkey` should provided on Testing section of [MACI site](https://appliedzkp.github.io/maci/testing.html#download-zkey-files).
> 
> Sure, who can help to upload the file?

Figured out the doc was edited by Koh Wei Jie. I don't know who maintains that storage at the moment. Maybe you can use S3 or some cloud storage service like Google Drive.

**Comment by corydickson** [comment]
We are currently using azure to host files at the moment and have a script to be updated that downloads them locally under `runTestsInCi.sh`. 

@chaosma If you want to send this my way I can upload this for you or can coordinate access.

**Pull request closed without merging**
