### PR TITLE
Migrate to node.js 12

### LINKED ISSUE #172: Migrate to node.js 12
According to the readme, MACI requires node.js 11:

```
You should have Node 11.14.0 installed. Use nvm to install it.
```

But this version is now unsupported and the increasing number of npm packages are starting to require `=10 || >=12`.

### PR DESCRIPTION
**Pull request by xuhcc**
~I ran the tests on node.js 12 and all of them passed.~

Resolves #172

### CODE REVIEW

**Comment by xuhcc** [comment]
CI build fails.

The cause of failure is outdated `scrypt` package which is a dependency of etherlime (https://github.com/LimeChain/etherlime/issues/314). It looks like etherlime is only used in `maci-contracts` package and probably can be replaced.

**Comment by xuhcc** [comment]
I've removed etherlime from tests but it is still used in `contracts/scripts/compileSol.sh` to compile contracts.

**Comment by weijiekoh** [comment]
Thanks for this PR!

May I suggest the solc binary instead of etherlime?

Here's an attempt at doing so: https://github.com/appliedzkp/maci/pull/174

**Comment by weijiekoh** [comment]
Just found out that switching to the `solc` binary will take more work the deploy script will have to read the ABI and .bin files via `fs.readFileSync`. Previously, Etherlime took care of that.

**Comment by weijiekoh** [comment]
Continued in #174.

**Pull request closed without merging**
