### PR TITLE
Restored correct verifier contracts + minor tweaks to tests

### PR DESCRIPTION
**Pull request by weijiekoh**

### CODE REVIEW

**Comment by weijiekoh** [comment]
@xuhcc I've published `0.2.4` to npm :smile:

**Comment by xuhcc** [comment]
@weijiekoh 

Some packages are not available on NPM (maci-cli 0.2.4, maci-circuits 0.2.4). I'm also getting this error when I try to use maci-cli 0.2.3 with maci-contracts 0.2.4 (probably due to dependency resolving in yarn):

```
ENOENT: no such file or directory, open './node_modules/maci-circuits/node_modules/circomlib/circuits/mux1.circom'
```

**Comment by weijiekoh** [comment]
My bad, the upload froze because I was on a poor connection. Please try again with `0.2.6`.

```
Successfully published:
 - maci-circuits@0.2.6
 - maci-cli@0.2.6
 - maci-config@0.2.6
 - maci-contracts@0.2.6
 - maci-core@0.2.6
 - maci-crypto@0.2.6
 - maci-domainobjs@0.2.6
 - maci-integrationtests@0.2.6
lerna success published 8 packages
```

**Comment by xuhcc** [comment]
Thanks!

**Pull request merged**
